### ISSUE TITLE
why does service.Start return a bool

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-common#1]
Why bother returning a bool? Is the error not enough?

https://github.com/tendermint/go-common/blob/master/service.go#L78

**Comment by melekes** [comment]
yeah, bool is superfluous

**Comment by ethanfrey** [comment]
If I remember correctly when I was writing test code, if I call Start() on a Service that is already running, it returns (false, nil). Only if I try to legitimately start it, but it fails in startup do I get an error.

The distinction is quite important to make it safe for reentrant calls.  The other approach would be to have a special error type like `ErrAlreadyStarted`, then check for that in your code explicitly. Kind of like if I make a db call in gorm, and get an error, I check if it is a RecordNotFound error, or whether there was a real error with the db query.

**Comment by melekes** [comment]
Ah, I see. Thanks. I must say I like `ErrAlreadyStarted` approach more (not just in Golang)
